name: wikiart-classification
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - libstdcxx-ng>=12
  - mkl<2024.1
  - intel-openmp<2024.1
  - pytorch::pytorch=2.4.1
  - pytorch::torchvision=0.19.1
  - pytorch-cuda=12.4
  - numpy<2
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - wandb
  - imagehash
